# WAS
server:
  port: 9090 #java -jar spring-5.jar --server.port=8083
  servlet:
    application-display-name: Hoyo Project Web Server
    session:
      timeout: 7200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro?serverTimezone=Asia/Seoul
    username: pro
    password: pro01!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   # none, update, create, create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

